import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const destination = new URL('../public/vendor/', import.meta.url);
await mkdir(destination, { recursive: true });
await build({
  entryPoints: [require.resolve('qrcode/lib/browser.js')],
  outfile: fileURLToPath(new URL('qrcode.js', destination)),
  bundle: true, platform: 'browser', format: 'esm', minify: true, target: 'es2020',
  banner: { js: '// node-qrcode 1.5.4 (MIT). See qrcode.LICENSE.txt. Generated by pnpm build:vendor.' }
});
const license = await readFile(require.resolve('qrcode/LICENSE'), 'utf8');
await writeFile(new URL('qrcode.LICENSE.txt', destination), license.trimEnd() + '\n');
console.log('QR Code pronto para o navegador, incluído em public/vendor.');
